server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        
        # 1. Le decimos a Nginx que acepte el archivo csr de Angular como página principal
        index  index.csr.html index.html;
        
        # 2. Redirigimos el enrutador para que Angular no dé error 404 al recargar
        try_files $uri $uri/ /index.csr.html;
    }

    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}